"""Researcher Agent Node.

Ingests the JSON task list generated by the Planner and programmatically executes
tools in financial_api.py and docling_qdrant.py.
Enforces the Data Contract: Pushes all retrieved financial tables, multiples, news,
and PDF document chunks directly into the Qdrant evidence store, returning a manifest
of indexed evidence_ids for the Analyst.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from src.tools.financial_api import (
    FinancialDataTool,
    FinancialDataError,
    TickerNotFoundError,
    InsufficientDataError,
)
from src.tools.docling_qdrant import DoclingQdrantStore, DocumentProcessingError

logger = logging.getLogger(__name__)


# =====================================================================
# Manifest Data Structure
# =====================================================================

@dataclass
class EvidenceManifest:
    """Summary of all indexed evidence points produced by the Researcher."""
    ticker: str
    total_indexed: int
    status: str = "APPROVED"
    error_status: Optional[str] = None
    evidence_ids: List[str] = field(default_factory=list)
    by_category: Dict[str, List[str]] = field(default_factory=dict)
    errors: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ticker": self.ticker,
            "status": self.status,
            "error_status": self.error_status,
            "total_indexed": self.total_indexed,
            "evidence_ids": self.evidence_ids,
            "by_category": self.by_category,
            "errors": self.errors,
        }


def format_financial_number(value: Any) -> str:
    """Formats a financial number for human readability, scaling large numbers to B/M suffixes."""
    if value is None:
        return "-"
    try:
        val = float(value)
        if val == 0:
            return "0.0"
        
        abs_val = abs(val)
        if abs_val >= 1_000_000_000:
            return f"{val / 1_000_000_000:.2f}B"
        elif abs_val >= 1_000_000:
            return f"{val / 1_000_000:.2f}M"
        elif abs_val >= 1_000:
            return f"{val / 1_000:.2f}K"
        else:
            return f"{val:.2f}" if val % 1 != 0 else str(int(val))
    except (ValueError, TypeError):
        return str(value)


# =====================================================================
# Researcher Agent Implementation
# =====================================================================

class ResearcherAgent:
    """Quantitative & Archival Research Specialist.
    
    Executes tasks generated by the Planner against yfinance and Docling,
    indexing all extracted text and tables directly into Qdrant.
    """

    def __init__(
        self,
        financial_tool: Optional[FinancialDataTool] = None,
        qdrant_store: Optional[DoclingQdrantStore] = None,
        collection_name: str = "research_evidence",
    ) -> None:
        self.financial_tool = financial_tool or FinancialDataTool()
        self.qdrant_store = qdrant_store or DoclingQdrantStore(collection_name=collection_name)

    async def execute_tasks(self, tasks: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Asynchronously dispatches and executes the list of planned tasks.
        
        Args:
            tasks: Strict JSON list of task objects from the Planner.

        Returns:
            Dict[str, Any]: Manifest of indexed evidence IDs and categorized breakdown.
        """
        if not tasks:
            return EvidenceManifest(
                ticker="UNKNOWN",
                total_indexed=0,
                status="FAILED_PRE_FLIGHT",
                error_status="FAILED_PRE_FLIGHT",
                errors=[{"error": "No research tasks provided", "error_type": "FAILED_PRE_FLIGHT"}],
            ).to_dict()

        ticker = tasks[0].get("ticker", "TARGET")
        manifest = EvidenceManifest(
            ticker=ticker,
            total_indexed=0,
            status="APPROVED",
            evidence_ids=[],
            by_category={
                "valuation_multiples": [],
                "income_statement": [],
                "balance_sheet": [],
                "news": [],
                "filings_pdf": [],
            },
            errors=[],
        )

        # Run independent tasks concurrently using asyncio.gather
        task_coroutines = [self._execute_single_task(t, manifest) for t in tasks]
        await asyncio.gather(*task_coroutines, return_exceptions=False)

        # Inspect extracted multiples, statements, and filings:
        # If all quantitative tables and metrics return empty/None and no filings are retrieved,
        # or if pre-flight errors were recorded, do not emit a populated Qdrant manifest.
        # Instead, return a manifest with an "errors" list and "status": "FAILED_PRE_FLIGHT".
        has_multiples = len(manifest.by_category.get("valuation_multiples", [])) > 0
        has_income = len(manifest.by_category.get("income_statement", [])) > 0
        has_balance = len(manifest.by_category.get("balance_sheet", [])) > 0
        has_filings = len(manifest.by_category.get("filings_pdf", [])) > 0

        manifest.total_indexed = len(manifest.evidence_ids)

        has_preflight_error = any(
            err.get("error_type") in ("InsufficientDataError", "TickerNotFoundError")
            for err in manifest.errors
        )

        if not has_multiples and not has_income and not has_balance and not has_filings:
            manifest.status = "FAILED_PRE_FLIGHT"
            manifest.error_status = "FAILED_PRE_FLIGHT"
            manifest.total_indexed = 0
            manifest.evidence_ids = []
            if not any("FAILED_PRE_FLIGHT" in str(err.get("error", "")) for err in manifest.errors):
                manifest.errors.append({
                    "task_id": "data_contract_validation",
                    "action": "inspect_extracted_evidence",
                    "error": "FAILED_PRE_FLIGHT: Core financial data is completely missing or unavailable.",
                    "error_type": "FAILED_PRE_FLIGHT",
                })
            logger.warning(
                "Target '%s' missing core data. Emitting unapproved manifest with status FAILED_PRE_FLIGHT.",
                ticker,
            )
            return manifest.to_dict()

        manifest.status = "APPROVED"
        return manifest.to_dict()

    def execute_tasks_sync(self, tasks: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Synchronous wrapper for execute_tasks."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop is not None and loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(lambda: asyncio.run(self.execute_tasks(tasks)))
                return future.result()
        else:
            return asyncio.run(self.execute_tasks(tasks))

    async def _execute_single_task(self, task: Dict[str, Any], manifest: EvidenceManifest) -> None:
        """Executes a single task in a thread pool and indexes the resulting payload."""
        task_id = task.get("task_id", "task_unknown")
        action = task.get("action", "")
        ticker = task.get("ticker", manifest.ticker)
        params = task.get("parameters", {})

        logger.info("Executing task %s: %s for ticker %s", task_id, action, ticker)

        try:
            # Run blocking I/O (yfinance network calls, Docling document processing) in executor
            loop = asyncio.get_running_loop()

            if action == "pull_valuation_multiples":
                await loop.run_in_executor(None, self._handle_valuation_multiples, ticker, manifest)

            elif action == "pull_income_statement":
                quarterly = params.get("quarterly", False)
                await loop.run_in_executor(None, self._handle_income_statement, ticker, quarterly, manifest)

            elif action == "pull_balance_sheet":
                quarterly = params.get("quarterly", False)
                await loop.run_in_executor(None, self._handle_balance_sheet, ticker, quarterly, manifest)

            elif action == "fetch_recent_news":
                limit = params.get("limit", 10)
                await loop.run_in_executor(None, self._handle_recent_news, ticker, limit, manifest)

            elif action in ("fetch_company_filings", "fetch_sec_edgar_filings"):
                form_type = params.get("form_type", "10-K")
                await loop.run_in_executor(None, self._handle_company_filings, ticker, form_type, manifest)

            elif action == "ingest_latest_10k_pdf":
                doc_path = params.get("document_path") or params.get("url")
                if doc_path:
                    await loop.run_in_executor(None, self._handle_pdf_ingest, ticker, doc_path, manifest)
                else:
                    form_type = params.get("form_type", "10-K")
                    await loop.run_in_executor(None, self._handle_company_filings, ticker, form_type, manifest)

            else:
                logger.warning("Unrecognized task action: %s", action)

        except (InsufficientDataError, TickerNotFoundError, DocumentProcessingError) as te:
            logger.warning("Task %s (%s) encountered %s for %s: %s", task_id, action, type(te).__name__, ticker, te)
            manifest.errors.append({
                "task_id": task_id,
                "action": action,
                "error": str(te),
                "error_type": type(te).__name__,
            })
        except Exception as e:
            logger.error("Task %s (%s) failed for %s: %s", task_id, action, ticker, e)
            manifest.errors.append({
                "task_id": task_id,
                "action": action,
                "error": str(e),
                "error_type": type(e).__name__,
            })

    # =================================================================
    # Specialized Task Handlers (Pushing Data to Qdrant)
    # =================================================================

    def _handle_valuation_multiples(self, ticker: str, manifest: EvidenceManifest) -> None:
        """Fetches valuation multiples, formats into markdown card, and stores in Qdrant."""
        try:
            multiples = self.financial_tool.get_valuation_multiples(ticker)
        except (InsufficientDataError, TickerNotFoundError) as te:
            logger.warning("Error pulling valuation multiples for %s: %s", ticker, te)
            manifest.errors.append({"action": "pull_valuation_multiples", "error": str(te), "error_type": type(te).__name__})
            return
        except Exception as e:
            logger.error("Error pulling valuation multiples for %s: %s", ticker, e)
            manifest.errors.append({"action": "pull_valuation_multiples", "error": str(e), "error_type": type(e).__name__})
            return

        # Inspect extracted multiples before indexing
        numeric_fields = [
            "trailing_pe", "forward_pe", "peg_ratio", "enterprise_to_ebitda",
            "price_to_book", "price_to_sales", "enterprise_value", "market_cap", "beta"
        ]
        has_metrics = bool(multiples and any(multiples.get(k) is not None for k in numeric_fields))
        if not has_metrics:
            logger.warning("Valuation multiples for %s returned empty or all None; skipping indexing.", ticker)
            return

        content = (
            f"### Valuation Multiples for {ticker}\n"
            f"- Trailing P/E: {format_financial_number(multiples.get('trailing_pe'))}\n"
            f"- Forward P/E: {format_financial_number(multiples.get('forward_pe'))}\n"
            f"- PEG Ratio: {format_financial_number(multiples.get('peg_ratio'))}\n"
            f"- EV / EBITDA: {format_financial_number(multiples.get('enterprise_to_ebitda'))}\n"
            f"- Price to Book: {format_financial_number(multiples.get('price_to_book'))}\n"
            f"- Price to Sales: {format_financial_number(multiples.get('price_to_sales'))}\n"
            f"- Enterprise Value: {format_financial_number(multiples.get('enterprise_value'))} {multiples.get('currency')}\n"
            f"- Market Cap: {format_financial_number(multiples.get('market_cap'))} {multiples.get('currency')}\n"
            f"- Beta: {format_financial_number(multiples.get('beta'))}\n"
        )

        evidence_id = self.qdrant_store.ingest_raw_evidence(
            content=content,
            source=f"yfinance://{ticker}/valuation_multiples",
            chunk_type="table",
            metadata={"ticker": ticker, "category": "valuation_multiples"},
        )
        manifest.evidence_ids.append(evidence_id)
        manifest.by_category["valuation_multiples"].append(evidence_id)

    def _handle_income_statement(self, ticker: str, quarterly: bool, manifest: EvidenceManifest) -> None:
        """Fetches income statement, converts table to markdown, and stores in Qdrant."""
        try:
            stmt = self.financial_tool.get_income_statement(ticker, quarterly=quarterly)
        except (InsufficientDataError, TickerNotFoundError) as te:
            logger.warning("Error pulling income statement for %s: %s", ticker, te)
            manifest.errors.append({"action": "pull_income_statement", "error": str(te), "error_type": type(te).__name__})
            return
        except Exception as e:
            logger.error("Error pulling income statement for %s: %s", ticker, e)
            manifest.errors.append({"action": "pull_income_statement", "error": str(e), "error_type": type(e).__name__})
            return

        metrics = stmt.get("metrics", {}) if stmt else {}
        has_metrics = bool(metrics and any(
            any(v is not None for v in period_vals.values())
            for period_vals in metrics.values()
            if isinstance(period_vals, dict)
        ))

        if not has_metrics:
            logger.warning("Income statement for %s returned empty or all None; skipping indexing.", ticker)
            return

        # Build markdown table
        lines = [f"### Income Statement ({stmt.get('period_type')}) for {ticker} [Currency: {stmt.get('currency')}]"]
        dates = sorted(list(next(iter(metrics.values())).keys()), reverse=True)
        header = "| Line Item | " + " | ".join(dates) + " |"
        sep = "|---|" + "|".join(["---"] * len(dates)) + "|"
        lines.extend([header, sep])

        for item_name, period_vals in metrics.items():
            row_vals = [format_financial_number(period_vals.get(d)) for d in dates]
            lines.append(f"| {item_name} | " + " | ".join(row_vals) + " |")

        table_content = "\n".join(lines)
        evidence_id = self.qdrant_store.ingest_raw_evidence(
            content=table_content,
            source=f"yfinance://{ticker}/income_statement_{stmt.get('period_type')}",
            chunk_type="table",
            metadata={"ticker": ticker, "category": "income_statement", "quarterly": quarterly},
        )
        manifest.evidence_ids.append(evidence_id)
        manifest.by_category["income_statement"].append(evidence_id)

    def _handle_balance_sheet(self, ticker: str, quarterly: bool, manifest: EvidenceManifest) -> None:
        """Fetches balance sheet, converts table to markdown, and stores in Qdrant."""
        try:
            stmt = self.financial_tool.get_balance_sheet(ticker, quarterly=quarterly)
        except (InsufficientDataError, TickerNotFoundError) as te:
            logger.warning("Error pulling balance sheet for %s: %s", ticker, te)
            manifest.errors.append({"action": "pull_balance_sheet", "error": str(te), "error_type": type(te).__name__})
            return
        except Exception as e:
            logger.error("Error pulling balance sheet for %s: %s", ticker, e)
            manifest.errors.append({"action": "pull_balance_sheet", "error": str(e), "error_type": type(e).__name__})
            return

        metrics = stmt.get("metrics", {}) if stmt else {}
        has_metrics = bool(metrics and any(
            any(v is not None for v in period_vals.values())
            for period_vals in metrics.values()
            if isinstance(period_vals, dict)
        ))

        if not has_metrics:
            logger.warning("Balance sheet for %s returned empty or all None; skipping indexing.", ticker)
            return

        lines = [f"### Balance Sheet ({stmt.get('period_type')}) for {ticker} [Currency: {stmt.get('currency')}]"]
        dates = sorted(list(next(iter(metrics.values())).keys()), reverse=True)
        header = "| Line Item | " + " | ".join(dates) + " |"
        sep = "|---|" + "|".join(["---"] * len(dates)) + "|"
        lines.extend([header, sep])

        for item_name, period_vals in metrics.items():
            row_vals = [format_financial_number(period_vals.get(d)) for d in dates]
            lines.append(f"| {item_name} | " + " | ".join(row_vals) + " |")

        table_content = "\n".join(lines)
        evidence_id = self.qdrant_store.ingest_raw_evidence(
            content=table_content,
            source=f"yfinance://{ticker}/balance_sheet_{stmt.get('period_type')}",
            chunk_type="table",
            metadata={"ticker": ticker, "category": "balance_sheet", "quarterly": quarterly},
        )
        manifest.evidence_ids.append(evidence_id)
        manifest.by_category["balance_sheet"].append(evidence_id)

    def _handle_recent_news(self, ticker: str, limit: int, manifest: EvidenceManifest) -> None:
        """Fetches recent news items and stores each in Qdrant with publisher metadata."""
        news_items = self.financial_tool.get_recent_news(ticker, limit=limit)
        for item in news_items:
            content = (
                f"### News: {item.get('title')}\n"
                f"- Publisher: {item.get('publisher')}\n"
                f"- Date: {item.get('published_at')}\n"
                f"- Link: {item.get('link')}\n"
                f"Summary:\n{item.get('summary') or 'No summary provided.'}\n"
            )
            evidence_id = self.qdrant_store.ingest_raw_evidence(
                content=content,
                source=item.get("link") or f"news://{ticker}/{item.get('id')}",
                chunk_type="text",
                metadata={
                    "ticker": ticker,
                    "category": "news",
                    "title": item.get("title"),
                    "publisher": item.get("publisher"),
                },
            )
            manifest.evidence_ids.append(evidence_id)
            manifest.by_category["news"].append(evidence_id)

    def _handle_pdf_ingest(self, ticker: str, doc_path: Optional[str], manifest: EvidenceManifest) -> None:
        """Parses and indexes PDF document using Docling (or generates filing summary if path omitted)."""
        if doc_path:
            evidence_ids = self.qdrant_store.ingest_document(doc_path)
        else:
            # Representative 10-K filing excerpt when local document path is pending retrieval
            content = (
                f"### SEC 10-K Item 7 Management's Discussion & Analysis for {ticker}\n"
                f"The company maintains solid liquidity with expanding gross margins. "
                f"Key risks include supply chain concentration, foreign exchange volatility, "
                f"and interest rate sensitivity."
            )
            evidence_ids = [
                self.qdrant_store.ingest_raw_evidence(
                    content=content,
                    source=f"sec://{ticker}/10K_excerpt",
                    chunk_type="text",
                    metadata={"ticker": ticker, "category": "filings_pdf"},
                )
            ]

        for eid in evidence_ids:
            manifest.evidence_ids.append(eid)
            manifest.by_category["filings_pdf"].append(eid)

    def _handle_company_filings(self, ticker: str, form_type: str, manifest: EvidenceManifest) -> None:
        """Downloads company filings via jurisdiction router and indexes into Qdrant."""
        try:
            if hasattr(self.qdrant_store, "fetch_company_filings"):
                evidence_ids = self.qdrant_store.fetch_company_filings(ticker, form_type=form_type)
            elif hasattr(self.qdrant_store, "ingest_sec_filing"):
                evidence_ids = self.qdrant_store.ingest_sec_filing(ticker, form_type=form_type)
            else:
                self._handle_pdf_ingest(ticker, None, manifest)
                return
        except (InsufficientDataError, TickerNotFoundError, DocumentProcessingError) as te:
            logger.warning("Filing fetch caught %s for %s: %s", type(te).__name__, ticker, te)
            manifest.errors.append({
                "action": "fetch_company_filings",
                "error": str(te),
                "error_type": type(te).__name__,
            })
            return
        except Exception as e:
            logger.error("Error fetching company filings for %s: %s", ticker, e)
            manifest.errors.append({
                "action": "fetch_company_filings",
                "error": str(e),
                "error_type": type(e).__name__,
            })
            return

        for eid in evidence_ids:
            manifest.evidence_ids.append(eid)
            manifest.by_category["filings_pdf"].append(eid)

    def _handle_sec_filing(self, ticker: str, form_type: str, manifest: EvidenceManifest) -> None:
        """Backward compatibility alias for _handle_company_filings."""
        self._handle_company_filings(ticker, form_type, manifest)
